import { Seafarer } from "../../core/models/seafarer.model";


export const seafarerTableColumns: {
    key: keyof Seafarer;
    label: string;
    visible?: boolean;
    selected?: boolean;
    type?: string;
}[] = [
        { key: 'Id', label: 'ID', selected: false, type: 'number' },
         { key: 'EmployeeCode', label: 'Employee Code', selected: true, type: 'text' },
        { key: 'KinName', label: 'Kin Name', selected: false, type: 'text' },
        { key: 'KinPhone', label: 'Kin Phone', selected: false, type: 'text' },
        { key: 'KinEmail', label: 'Kin Email', selected: false, type: 'text' },
        { key: 'PassPortIssueDate', label: 'Passport Issue Date', selected: true, type: 'date' },
        { key: 'EmpId', label: 'Employee ID', selected: false, type: 'number' },
        { key: 'VisaSponsorId', label: 'Visa Sponsor ID', selected: false, type: 'number' },
        { key: 'Remarks', label: 'Remarks', selected: false, type: 'text' },
        { key: 'VisaIssueDate', label: 'Visa Issue Date', selected: true, type: 'date' },
        { key: 'VisaExpiryDate', label: 'Visa Expiry Date', selected: true, type: 'date' },
        { key: 'EmployeeName', label: 'Employee Name', selected: false, type: 'text' },
        { key: 'SponsorName', label: 'Sponsor Name', selected: false, type: 'text' },
       
        { key: 'JobName', label: 'Job Name', selected: true, type: 'text' },
        { key: 'Nationality', label: 'Nationality', selected: true, type: 'text' },
        { key: 'BirthDate', label: 'Date of Birth', selected: true, type: 'date' },
        { key: 'Phone', label: 'Phone', selected: true, type: 'text' },
        { key: 'Mobile', label: 'Mobile', selected: true, type: 'text' },
        { key: 'Email', label: 'Email', selected: true, type: 'text' },
        { key: 'NationalId', label: 'National ID', selected: true, type: 'text' },
        { key: 'EmploymentDate', label: 'Employment Date', selected: true, type: 'date' },
        { key: 'InsuranceDate', label: 'Insurance Date', selected: true, type: 'date' },
        { key: 'PassportExpireDate', label: 'Passport Expiry Date', selected: true, type: 'date' },
        { key: 'PassportNumber', label: 'Passport Number', selected: true, type: 'text' },
        { key: 'Age', label: 'Age', selected: true, type: 'text' },
        { key: 'EmployeeNameAR', label: 'Employee Name (AR)', selected: false, type: 'text' },
        { key: 'EmployeeNameEN', label: 'Employee Name (EN)', selected: false, type: 'text' },
        { key: 'JobNameEN', label: 'Job Name (EN)', selected: false, type: 'text' },
        { key: 'JobNameAR', label: 'Job Name (AR)', selected: false, type: 'text' },
        { key: 'Salary', label: 'Salary', selected: false, type: 'currency' },
        { key: 'Address', label: 'Address', selected: false, type: 'text' },
        { key: 'Gender', label: 'Gender', selected: false, type: 'text' },
        { key: 'Religion', label: 'Religion', selected: false, type: 'text' },
        { key: 'InsuranceNumber', label: 'Insurance Number', selected: false, type: 'text' },
        { key: 'Area', label: 'Area', selected: false, type: 'text' },
        { key: 'MilitaryServiceExpireDate', label: 'Military Service Expiry', selected: false, type: 'date' },
        { key: 'SyndicateCardNumber', label: 'Syndicate Card Number', selected: false, type: 'text' },
        { key: 'SyndicateExpirationDate', label: 'Syndicate Expiry Date', selected: false, type: 'date' },
        { key: 'BusinessPhone', label: 'Business Phone', selected: false, type: 'text' },
        { key: 'BirthPlace', label: 'Birth Place', selected: false, type: 'text' },
        { key: 'NationalIdExpiryDate', label: 'National ID Expiry', selected: false, type: 'date' },
        { key: 'Company', label: 'Company', selected: false, type: 'text' },
        { key: 'PostCategoryLevel', label: 'Post Category Level', selected: false, type: 'text' },
        { key: 'Tier', label: 'Tier', selected: false, type: 'text' },
        { key: 'DrivingLicenseNumber', label: 'Driving License', selected: false, type: 'text' },
        { key: 'WorkPermit', label: 'Work Permit', selected: false, type: 'text' },
        { key: 'PermitNumber', label: 'Permit Number', selected: false, type: 'text' },
        { key: 'BloodType', label: 'Blood Type', selected: false, type: 'text' },
        { key: 'WorkLocation', label: 'Work Location', selected: false, type: 'text' },
        { key: 'PermitExpirationDate', label: 'Permit Expiry Date', selected: false, type: 'date' },
        { key: 'Notes', label: 'Notes', selected: false, type: 'text' },
        { key: 'MedicalInsuranceAmount', label: 'Medical Insurance Amount', selected: false, type: 'currency' },
        { key: 'InsuranceTitle', label: 'Insurance Title', selected: false, type: 'text' },
        { key: 'InsuranceOffice', label: 'Insurance Office', selected: false, type: 'text' },
        { key: 'MedicalInsuranceNo', label: 'Medical Insurance No', selected: false, type: 'text' },
        { key: 'MedicalInsuranceDate', label: 'Medical Insurance Date', selected: false, type: 'date' },
        { key: 'GraduationYear', label: 'Graduation Year', selected: false, type: 'date' },
        { key: 'PostGraduateDegree', label: 'Post Graduate Degree', selected: false, type: 'text' },
        { key: 'PostGraduateUniversity', label: 'Post Graduate University', selected: false, type: 'text' },
        { key: 'PostGraduateSpecialty', label: 'Post Graduate Specialty', selected: false, type: 'text' },
        { key: 'PostGraduateGrade', label: 'Post Graduate Grade', selected: false, type: 'text' },
        { key: 'PropationEndDate', label: 'Probation End Date', selected: false, type: 'date' },
        { key: 'EmpManager', label: 'Employee Manager', selected: false, type: 'text' },
        { key: 'NameOfSpouse', label: 'Name of Spouse', selected: false, type: 'text' },
        { key: 'NoOfChildren', label: 'No of Children', selected: false, type: 'number' },
        { key: 'BodyWeight', label: 'Body Weight', selected: false, type: 'number' },
        { key: 'Height', label: 'Height', selected: false, type: 'number' },
        { key: 'VisaUAEIdNO', label: 'Visa UAE ID', selected: false, type: 'text' },
        { key: 'NearestAirport', label: 'Nearest Airport', selected: false, type: 'text' },
        { key: 'ResidenceNumber', label: 'Residence Number', selected: false, type: 'text' },
        { key: 'SkypeID', label: 'Skype ID', selected: false, type: 'text' },
        { key: 'PermanentAddressHomeCountry', label: 'Permanent Address', selected: false, type: 'text' },
        { key: 'ContactNumberHomeCountry', label: 'Contact Number Home Country', selected: false, type: 'text' },
        { key: 'ContactNameAndNumberDuringEmergenciesUAE', label: 'Emergency Contact UAE', selected: false, type: 'text' },
        { key: 'ContactNameAndNumberDuringEmergenciesHome', label: 'Emergency Contact Home', selected: false, type: 'text' },
        { key: 'SeamanBookNO', label: 'Seaman Book Number', selected: false, type: 'text' },
        { key: 'SeamanIssueDate', label: 'Seaman Issue Date', selected: false, type: 'date' },
        { key: 'SeamanExpiryDate', label: 'Seaman Expiry Date', selected: false, type: 'date' },
        { key: 'CicpaNO', label: 'Cicpa Number', selected: false, type: 'text' },
        { key: 'CicpaIssueDate', label: 'Cicpa Issue Date', selected: false, type: 'date' },
        { key: 'CicpaExpiryDate', label: 'Cicpa Expiry Date', selected: false, type: 'date' },
        { key: 'Declaration', label: 'Declaration', selected: false, type: 'text' },
        { key: 'SignedOffFromAShipDueToMedicalReason', label: 'Signed Off Due to Medical', selected: false, type: 'boolean' },
        { key: 'SignedOffFromAShipDueToMedicalReasonComment', label: 'Signed Off Comment', selected: false, type: 'text' },
        { key: 'UndergoneAnyMdicalOperation', label: 'Medical Operation', selected: false, type: 'text' },
        { key: 'UndergoneAnyMdicalOperationComment', label: 'Medical Operation Comment', selected: false, type: 'text' },
        { key: 'DoctorConsultation', label: 'Doctor Consultation', selected: false, type: 'text' },
        { key: 'DoctorConsultationComment', label: 'Doctor Consultation Comment', selected: false, type: 'text' },
        { key: 'HealthOrDisabilityProblem', label: 'Health/Disability Problem', selected: false, type: 'text' },
        { key: 'HealthOrDisabilityProblemComment', label: 'Health/Disability Comment', selected: false, type: 'text' },
        { key: 'InquiryOrInvolvedMaritimeAccident', label: 'Maritime Accident', selected: false, type: 'text' },
        { key: 'InquiryOrInvolvedMaritimeAccidentComment', label: 'Maritime Accident Comment', selected: false, type: 'text' },
        { key: 'LicenseSuspendedOrRevoked', label: 'License Suspended', selected: false, type: 'text' },
        { key: 'LicenseSuspendedOrRevokedComment', label: 'License Suspended Comment', selected: false, type: 'text' },
        { key: 'ConfirmationInsuranceDate', label: 'Confirmation Insurance Date', selected: false, type: 'date' },
        { key: 'MaritalStatus', label: 'Marital Status', selected: false, type: 'text' },
        { key: 'Status', label: 'Status', selected: false, type: 'number' },
        { key: 'Basic', label: 'Basic', selected: false, type: 'text' },
        { key: 'Advanced', label: 'Advanced', selected: false, type: 'text' },
        { key: 'FullLicence', label: 'Full Licence', selected: false, type: 'text' },
        { key: 'Maintenance', label: 'Maintenance', selected: false, type: 'text' },
        { key: 'JoiningCost', label: 'Joining Cost', selected: false, type: 'currency' },
        { key: 'PreJoiningCost', label: 'Pre-Joining Cost', selected: false, type: 'currency' },
        { key: 'OnBoardingCost', label: 'Onboarding Cost', selected: false, type: 'currency' }
    ];
